import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1779313578349 implements MigrationInterface {
    name = '1705InitialSchema1779313578349'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'cashier')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying, "password" character varying NOT NULL, "pin" character varying, "full_name" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'cashier', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."shifts_status_enum" AS ENUM('open', 'closed')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "opening_cash" numeric(10,2) NOT NULL, "closing_cash" numeric(10,2), "status" "public"."shifts_status_enum" NOT NULL DEFAULT 'open', "opened_at" TIMESTAMP NOT NULL DEFAULT now(), "closed_at" TIMESTAMP, "notes" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_type_enum" AS ENUM('dine_in', 'takeaway', 'delivery')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('open', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_number" character varying NOT NULL, "type" "public"."orders_type_enum" NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'open', "table_number" integer, "table_id" uuid, "customer_name" character varying, "customer_phone" character varying, "delivery_address" character varying, "notes" character varying, "subtotal" numeric(10,2) NOT NULL, "discount_type" character varying, "discount_value" numeric(10,2), "discount_amount" numeric(10,2) NOT NULL, "tax_rate" numeric(5,2) NOT NULL, "tax_amount" numeric(10,2) NOT NULL, "service_charge_rate" numeric(5,2) NOT NULL, "service_charge_amount" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "cashier_id" uuid NOT NULL, "shift_id" uuid NOT NULL, "confirmed_at" TIMESTAMP, "completed_at" TIMESTAMP, "cancelled_at" TIMESTAMP, "cancel_reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "menu_item_id" character varying NOT NULL, "variant_id" character varying, "item_name_ar" character varying NOT NULL, "item_name_en" character varying NOT NULL, "unit_price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "subtotal" numeric(10,2) NOT NULL, "notes" character varying, "is_voided" boolean NOT NULL DEFAULT false, "void_reason" character varying, "voided_by" character varying, "voided_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item_addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_item_id" uuid NOT NULL, "addon_id" character varying NOT NULL, "addon_name" character varying NOT NULL, "price" numeric(10,2) NOT NULL, CONSTRAINT "PK_4330667b2b406c8e4fb6214b235" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "from_status" character varying, "to_status" character varying NOT NULL, "changed_by" character varying, "notes" character varying, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8e29911f9edfb67c6810f56ac5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tables_status_enum" AS ENUM('available', 'occupied', 'reserved')`);
        await queryRunner.query(`CREATE TABLE "tables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "table_number" integer NOT NULL, "capacity" integer NOT NULL DEFAULT '4', "status" "public"."tables_status_enum" NOT NULL DEFAULT 'available', "location" character varying, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_334ee7fca06f1fe624c1ebfd34f" UNIQUE ("table_number"), CONSTRAINT "PK_7cf2aca7af9550742f855d4eb69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weekly_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "week_number" integer NOT NULL, "year" integer NOT NULL, "week_start_date" date NOT NULL, "week_end_date" date NOT NULL, "total_orders" integer NOT NULL DEFAULT '0', "completed_orders" integer NOT NULL DEFAULT '0', "cancelled_orders" integer NOT NULL DEFAULT '0', "total_revenue" numeric(10,2) NOT NULL DEFAULT '0', "total_cost" numeric(10,2) NOT NULL DEFAULT '0', "gross_profit" numeric(10,2) NOT NULL DEFAULT '0', "net_profit" numeric(10,2) NOT NULL DEFAULT '0', "average_order_value" numeric(10,2) NOT NULL DEFAULT '0', "order_growth_percentage" numeric(5,2) NOT NULL DEFAULT '0', "revenue_growth_percentage" numeric(5,2) NOT NULL DEFAULT '0', "daily_breakdown" jsonb NOT NULL DEFAULT '[]', "top_selling_products" jsonb NOT NULL DEFAULT '[]', "payment_methods_breakdown" jsonb NOT NULL DEFAULT '{}', "busiest_day" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7e57ce3fdf34bda8ca3704226e3" UNIQUE ("week_number", "year"), CONSTRAINT "PK_1a8cd4b8d43d7a359597b75f792" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text NOT NULL, "updated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "monthly_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "month" integer NOT NULL, "year" integer NOT NULL, "month_start_date" date NOT NULL, "month_end_date" date NOT NULL, "total_orders" integer NOT NULL DEFAULT '0', "completed_orders" integer NOT NULL DEFAULT '0', "cancelled_orders" integer NOT NULL DEFAULT '0', "total_revenue" numeric(10,2) NOT NULL DEFAULT '0', "total_cost" numeric(10,2) NOT NULL DEFAULT '0', "gross_profit" numeric(10,2) NOT NULL DEFAULT '0', "net_profit" numeric(10,2) NOT NULL DEFAULT '0', "profit_margin_percentage" numeric(5,2) NOT NULL DEFAULT '0', "average_order_value" numeric(10,2) NOT NULL DEFAULT '0', "order_growth_percentage" numeric(5,2) NOT NULL DEFAULT '0', "revenue_growth_percentage" numeric(5,2) NOT NULL DEFAULT '0', "weekly_breakdown" jsonb NOT NULL DEFAULT '[]', "daily_breakdown" jsonb NOT NULL DEFAULT '[]', "top_selling_products" jsonb NOT NULL DEFAULT '[]', "worst_selling_products" jsonb NOT NULL DEFAULT '[]', "payment_methods_breakdown" jsonb NOT NULL DEFAULT '{}', "customer_stats" jsonb NOT NULL DEFAULT '{}', "busiest_day" character varying, "slowest_day" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e16e33511068662766433cebe96" UNIQUE ("month", "year"), CONSTRAINT "PK_6d42f2bb59ee092e3349e2b8992" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_generation_logs_report_type_enum" AS ENUM('daily', 'weekly', 'monthly')`);
        await queryRunner.query(`CREATE TYPE "public"."report_generation_logs_status_enum" AS ENUM('pending', 'generating', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."report_generation_logs_triggered_by_enum" AS ENUM('auto', 'manual')`);
        await queryRunner.query(`CREATE TABLE "report_generation_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_type" "public"."report_generation_logs_report_type_enum" NOT NULL, "report_id" uuid, "status" "public"."report_generation_logs_status_enum" NOT NULL DEFAULT 'pending', "error_message" text, "generation_time_ms" integer, "triggered_by" "public"."report_generation_logs_triggered_by_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52f97a462c69c8efa79749a8441" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "report_date" date NOT NULL, "total_orders" integer NOT NULL DEFAULT '0', "completed_orders" integer NOT NULL DEFAULT '0', "cancelled_orders" integer NOT NULL DEFAULT '0', "pending_orders" integer NOT NULL DEFAULT '0', "new_customers" integer NOT NULL DEFAULT '0', "returning_customers" integer NOT NULL DEFAULT '0', "total_revenue" numeric(10,2) NOT NULL DEFAULT '0', "total_cost" numeric(10,2) NOT NULL DEFAULT '0', "gross_profit" numeric(10,2) NOT NULL DEFAULT '0', "net_profit" numeric(10,2) NOT NULL DEFAULT '0', "average_order_value" numeric(10,2) NOT NULL DEFAULT '0', "top_selling_products" jsonb NOT NULL DEFAULT '[]', "payment_methods_breakdown" jsonb NOT NULL DEFAULT '{}', "hourly_distribution" jsonb NOT NULL DEFAULT '[]', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_91d743613757dd38b07676c9bda" UNIQUE ("report_date"), CONSTRAINT "PK_9c061cec58b95e2cc8ed285db09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_ar" character varying NOT NULL, "name_en" character varying NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "name_ar" character varying NOT NULL, "name_en" character varying NOT NULL, "description_ar" character varying, "description_en" character varying, "base_price" numeric(10,2) NOT NULL, "image_url" character varying, "tax_group" character varying NOT NULL DEFAULT 'standard', "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_57e6188f929e5dc6919168620c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "menu_item_id" uuid NOT NULL, "name" character varying NOT NULL, "price_adjustment" numeric(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_672d13d1a6de0197f20c6babb5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('paid', 'refunded', 'partial_refund')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying NOT NULL, "order_id" uuid NOT NULL, "subtotal" numeric(10,2) NOT NULL, "discount_amount" numeric(10,2) NOT NULL, "discount_type" character varying, "tax_rate" numeric(5,2) NOT NULL, "tax_amount" numeric(10,2) NOT NULL, "service_charge_rate" numeric(5,2) NOT NULL, "service_charge_amount" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "status" "public"."invoices_status_enum" NOT NULL, "issued_by" uuid NOT NULL, "issued_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('cash', 'card', 'wallet', 'online')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "reference_number" character varying, "card_last_four" character varying, "processed_by" uuid NOT NULL, "received_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "payment_id" uuid, "amount" numeric(10,2) NOT NULL, "reason" character varying NOT NULL, "approved_by" uuid NOT NULL, "refunded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cash_drawers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "shift_id" uuid NOT NULL, "opening_balance" numeric(10,2) NOT NULL, "total_cash_in" numeric(10,2) NOT NULL DEFAULT '0', "total_cash_out" numeric(10,2) NOT NULL DEFAULT '0', "expected_balance" numeric(10,2) NOT NULL DEFAULT '0', "actual_balance" numeric(10,2), "difference" numeric(10,2), "notes" character varying, "opened_at" TIMESTAMP NOT NULL DEFAULT now(), "closed_at" TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56eb82c6aff5b19530c70a6a129" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name_ar" character varying NOT NULL, "name_en" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cd49fb3dc0558f02cb6fe6cc138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_dc1e84f1d1e75e990952c40859c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_3d36410e89a795172fa6e0dd968" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_f6a81e17c5548c6e49f260c9dad" FOREIGN KEY ("cashier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a47d559598368bc78800dd5175b" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_addons" ADD CONSTRAINT "FK_a1ebcd9f3a3928abad0f6f2484f" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_logs" ADD CONSTRAINT "FK_994abe9a55f6bbb2b8cef54761d" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_items" ADD CONSTRAINT "FK_20cff56c44dd4fe52d5aa2b96f8" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variants" ADD CONSTRAINT "FK_b130fcbd56b756dec523ac072fa" FOREIGN KEY ("menu_item_id") REFERENCES "menu_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ea83c3b911906a3578de2340fdf" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_583c9037bc0cbe84ab512a33580" FOREIGN KEY ("issued_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d16692ba65db3041ca5961cb0fe" FOREIGN KEY ("processed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_bbe1a0623e423441c89937a74bd" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_7f48aa5d56c42aeb495db016683" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_ff3564f0e4925cec019b1a60144" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_drawers" ADD CONSTRAINT "FK_18ec9d92733206f797cc0207fc2" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cash_drawers" DROP CONSTRAINT "FK_18ec9d92733206f797cc0207fc2"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_ff3564f0e4925cec019b1a60144"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_7f48aa5d56c42aeb495db016683"`);
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_bbe1a0623e423441c89937a74bd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d16692ba65db3041ca5961cb0fe"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_583c9037bc0cbe84ab512a33580"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ea83c3b911906a3578de2340fdf"`);
        await queryRunner.query(`ALTER TABLE "variants" DROP CONSTRAINT "FK_b130fcbd56b756dec523ac072fa"`);
        await queryRunner.query(`ALTER TABLE "menu_items" DROP CONSTRAINT "FK_20cff56c44dd4fe52d5aa2b96f8"`);
        await queryRunner.query(`ALTER TABLE "order_status_logs" DROP CONSTRAINT "FK_994abe9a55f6bbb2b8cef54761d"`);
        await queryRunner.query(`ALTER TABLE "order_item_addons" DROP CONSTRAINT "FK_a1ebcd9f3a3928abad0f6f2484f"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a47d559598368bc78800dd5175b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_f6a81e17c5548c6e49f260c9dad"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_3d36410e89a795172fa6e0dd968"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_dc1e84f1d1e75e990952c40859c"`);
        await queryRunner.query(`DROP TABLE "addons"`);
        await queryRunner.query(`DROP TABLE "cash_drawers"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "variants"`);
        await queryRunner.query(`DROP TABLE "menu_items"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "daily_reports"`);
        await queryRunner.query(`DROP TABLE "report_generation_logs"`);
        await queryRunner.query(`DROP TYPE "public"."report_generation_logs_triggered_by_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_generation_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_generation_logs_report_type_enum"`);
        await queryRunner.query(`DROP TABLE "monthly_reports"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "weekly_reports"`);
        await queryRunner.query(`DROP TABLE "tables"`);
        await queryRunner.query(`DROP TYPE "public"."tables_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_status_logs"`);
        await queryRunner.query(`DROP TABLE "order_item_addons"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_type_enum"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
