import { DashboardData } from '@/components/admin/DashboardProvider';

export const mockDashboardData: DashboardData = {
  stat_cards: {
    total_revenue: 15420.50,
    total_orders: 342,
    average_order_value: 45.06,
    items_sold: 1240,
    growth: {
      revenue_pct: 12.5,
      orders_pct: 8.3,
      avg_order_pct: 3.8,
      items_sold_pct: 15.2,
    },
  },
  revenue_chart: [
    { day_name: 'Monday', day_date: '2026-05-18', revenue: 2100.00 },
    { day_name: 'Tuesday', day_date: '2026-05-19', revenue: 2450.75 },
    { day_name: 'Wednesday', day_date: '2026-05-20', revenue: 2200.25 },
    { day_name: 'Thursday', day_date: '2026-05-21', revenue: 3150.00 },
    { day_name: 'Friday', day_date: '2026-05-22', revenue: 3800.50 },
    { day_name: 'Saturday', day_date: '2026-05-23', revenue: 1720.00 },
  ],
  category_breakdown: [
    {
      category_id: '1',
      name_en: 'Appetizers',
      name_ar: 'المقبلات',
      revenue: 3240.00,
      order_count: 85,
      percentage: 21.0,
    },
    {
      category_id: '2',
      name_en: 'Main Courses',
      name_ar: 'الأطباق الرئيسية',
      revenue: 6580.00,
      order_count: 156,
      percentage: 42.7,
    },
    {
      category_id: '3',
      name_en: 'Beverages',
      name_ar: 'المشروبات',
      revenue: 2890.50,
      order_count: 201,
      percentage: 18.8,
    },
    {
      category_id: '4',
      name_en: 'Desserts',
      name_ar: 'الحلويات',
      revenue: 2710.00,
      order_count: 98,
      percentage: 17.6,
    },
  ],
  most_ordered: [
    {
      menu_item_id: '1',
      name_en: 'Grilled Salmon',
      name_ar: 'السلمون المشوي',
      quantity: 125,
      revenue: 2500.00,
      percentage: 10.1,
    },
    {
      menu_item_id: '2',
      name_en: 'Caesar Salad',
      name_ar: 'سلطة قيصر',
      quantity: 98,
      revenue: 980.00,
      percentage: 7.9,
    },
    {
      menu_item_id: '3',
      name_en: 'Chicken Tikka Masala',
      name_ar: 'دجاج تيكا ماسالا',
      quantity: 112,
      revenue: 2240.00,
      percentage: 9.1,
    },
    {
      menu_item_id: '4',
      name_en: 'Espresso',
      name_ar: 'إسبريسو',
      quantity: 245,
      revenue: 735.00,
      percentage: 5.9,
    },
    {
      menu_item_id: '5',
      name_en: 'Chocolate Cake',
      name_ar: 'كيك الشوكولاتة',
      quantity: 87,
      revenue: 870.00,
      percentage: 7.0,
    },
  ],
  status_summary: {
    completed: 285,
    pending: 42,
    cancelled: 15,
  },
  generated_at: new Date().toISOString(),
};

export const mockCategories = [
  { id: '1', name_en: 'Appetizers', name_ar: 'المقبلات', sort_order: 1, is_active: true },
  { id: '2', name_en: 'Main Courses', name_ar: 'الأطباق الرئيسية', sort_order: 2, is_active: true },
  { id: '3', name_en: 'Beverages', name_ar: 'المشروبات', sort_order: 3, is_active: true },
  { id: '4', name_en: 'Desserts', name_ar: 'الحلويات', sort_order: 4, is_active: true },
];

export const mockMenuItems = [
  {
    id: '1',
    name_en: 'Grilled Salmon',
    name_ar: 'السلمون المشوي',
    description_en: 'Fresh salmon fillet with lemon butter sauce',
    description_ar: 'شريحة سلمون طازة مع صلصة زبدة الليمون',
    base_price: 280.00,
    category_id: '2',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 1,
  },
  {
    id: '2',
    name_en: 'Caesar Salad',
    name_ar: 'سلطة قيصر',
    description_en: 'Classic Caesar salad with parmesan',
    description_ar: 'سلطة قيصر كلاسيكية مع البارميزان',
    base_price: 95.00,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 1,
  },
  {
    id: '3',
    name_en: 'Chicken Tikka Masala',
    name_ar: 'دجاج تيكا ماسالا',
    description_en: 'Tender chicken in creamy tomato sauce',
    description_ar: 'دجاج طري في صلصة طماطم كريمية',
    base_price: 200.00,
    category_id: '2',
    image_url: 'https://images.unsplash.com/photo-1603894542802-f8b3c63ef58d?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 2,
  },
  {
    id: '4',
    name_en: 'Bruschetta',
    name_ar: 'بروسكيتا',
    description_en: 'Toasted bread with tomato and basil',
    description_ar: 'خبز محمص مع الطماطم والريحان',
    base_price: 75.00,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 2,
  },
  {
    id: '5',
    name_en: 'Espresso',
    name_ar: 'إسبريسو',
    description_en: 'Strong Italian espresso',
    description_ar: 'قهوة إسبريسو إيطالية قوية',
    base_price: 30.00,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 1,
  },
  {
    id: '6',
    name_en: 'Fresh Orange Juice',
    name_ar: 'عصير برتقال طازج',
    description_en: 'Freshly squeezed orange juice',
    description_ar: 'عصير برتقال معصور حديثاً',
    base_price: 40.00,
    category_id: '3',
    image_url: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 2,
  },
  {
    id: '7',
    name_en: 'Chocolate Cake',
    name_ar: 'كيك الشوكولاتة',
    description_en: 'Rich chocolate cake with ganache',
    description_ar: 'كعكة شوكولاتة غنية مع جانش',
    base_price: 85.00,
    category_id: '4',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 1,
  },
  {
    id: '8',
    name_en: 'Cheesecake',
    name_ar: 'كيك الجبن',
    description_en: 'New York style cheesecake',
    description_ar: 'كعكة جبن على طريقة نيويورك',
    base_price: 95.00,
    category_id: '4',
    image_url: 'https://images.unsplash.com/photo-1533134242443-742ce1801520?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 2,
  },
  {
    id: '9',
    name_en: 'Beef Steak',
    name_ar: 'ستيك لحم',
    description_en: 'Premium beef steak with herbs',
    description_ar: 'ستيك لحم ممتاز مع الأعشاب',
    base_price: 320.00,
    category_id: '2',
    image_url: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd57f86?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 3,
  },
  {
    id: '10',
    name_en: 'Vegetable Soup',
    name_ar: 'حساء الخضار',
    description_en: 'Seasonal fresh vegetable soup',
    description_ar: 'حساء خضار طازج موسمي',
    base_price: 60.00,
    category_id: '1',
    image_url: 'https://images.unsplash.com/photo-1547592166-7aae4d755744?w=400&h=300&fit=crop',
    is_active: true,
    sort_order: 3,
  },
];

export const mockTables = [
  { id: '1', number: 1, capacity: 4, status: 'available' },
  { id: '2', number: 2, capacity: 4, status: 'occupied' },
  { id: '3', number: 3, capacity: 6, status: 'reserved' },
  { id: '4', number: 4, capacity: 2, status: 'available' },
  { id: '5', number: 5, capacity: 6, status: 'occupied' },
];

export const mockOrders = [
  {
    id: '1',
    table_id: '2',
    table_number: 2,
    status: 'preparing',
    total_before_tax: 450.00,
    tax_amount: 67.50,
    total: 517.50,
    created_at: '2026-05-21T10:30:00Z',
    updated_at: '2026-05-21T10:35:00Z',
    items: [
      { id: 'oi1', menu_item_id: '1', name_en: 'Grilled Salmon', quantity: 1, unit_price: 280.00, total: 280.00 },
      { id: 'oi2', menu_item_id: '3', name_en: 'Chicken Tikka Masala', quantity: 1, unit_price: 200.00, total: 200.00 },
    ],
  },
  {
    id: '2',
    table_id: '5',
    table_number: 5,
    status: 'completed',
    total_before_tax: 300.00,
    tax_amount: 45.00,
    total: 345.00,
    created_at: '2026-05-21T09:45:00Z',
    updated_at: '2026-05-21T10:15:00Z',
    items: [
      { id: 'oi3', menu_item_id: '2', name_en: 'Caesar Salad', quantity: 2, unit_price: 95.00, total: 190.00 },
      { id: 'oi4', menu_item_id: '5', name_en: 'Espresso', quantity: 2, unit_price: 30.00, total: 60.00 },
    ],
  },
  {
    id: '3',
    table_id: '1',
    table_number: 1,
    status: 'completed',
    total_before_tax: 540.00,
    tax_amount: 81.00,
    total: 621.00,
    created_at: '2026-05-21T11:15:00Z',
    updated_at: '2026-05-21T12:00:00Z',
    items: [
      { id: 'oi5', menu_item_id: '9', name_en: 'Beef Steak', quantity: 2, unit_price: 320.00, total: 640.00 },
      { id: 'oi6', menu_item_id: '6', name_en: 'Fresh Orange Juice', quantity: 2, unit_price: 40.00, total: 80.00 },
    ],
  },
  {
    id: '4',
    table_id: '3',
    table_number: 3,
    status: 'ready',
    total_before_tax: 200.00,
    tax_amount: 30.00,
    total: 230.00,
    created_at: '2026-05-21T12:30:00Z',
    updated_at: '2026-05-21T12:50:00Z',
    items: [
      { id: 'oi7', menu_item_id: '7', name_en: 'Chocolate Cake', quantity: 2, unit_price: 85.00, total: 170.00 },
      { id: 'oi8', menu_item_id: '5', name_en: 'Espresso', quantity: 1, unit_price: 30.00, total: 30.00 },
    ],
  },
];
